import { Inter } from "next/font/google";

import SessionProvider from "./session-provider";
import { getServerSession } from "next-auth";
import UserState from "@/context/userContext/userState";
// import './globals.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <UserState>
          <body className={inter.className}>{children}</body>
        </UserState>
      </SessionProvider>
    </html>
  );
}
